name: release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    branches:
    - release-*
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install meson
        run: pip install meson ninja
      - name: Install dependencies
        run: |
          sudo apt-get install -y check libudev-dev libxkbcommon-dev libdrm-dev libgbm-dev libegl1-mesa-dev libgles-dev libpango1.0-dev libsystemd-dev
      - name: Install libtsm
        run: |
          pip install cmake
          curl -L -o libtsm.tar.gz $(curl -s https://api.github.com/repos/Aetf/libtsm/releases/latest \
            | grep "tarball_url" \
            | awk '{ print $2 }' \
            | sed 's/,$//'       \
            | sed 's/"//g' )
          mkdir libtsm
          tar -xf libtsm.tar.gz -C libtsm --strip 1
          cd libtsm
          cmake -Bbuilddir
          cmake --build builddir
          sudo cmake --install builddir
      - name: Meson setup
        run: meson setup builddir/
      - name: Create source distribution
        # no unit tests yet
        run: meson dist -C builddir/
      - name: Create release note
        run: tools/extract_release_note.py NEWS ${{ github.workspace }}-release-note.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-files
          path: |
            builddir/meson-dist/*
            ${{ github.workspace }}-release-note.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        # only actually create the release when run on tag
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: builddir/meson-dist/*
          body_path: ${{ github.workspace }}-release-note.txt
